public class NameOps {

    public static String printMethodCall(String method, String name) {
        return method + "(" + name + "): ";
    }

    public static String whoIsAwesome(String name) {
        return name + "is awesome!";
    }

    public static int indexOfFirstSpace(String name) {
        for(int i = 0; i < string.length() - 1; i++)
        {
            char niceChara = charAt(i);
            if(niceChara == ' ') {
                return i;
            } else {
                return -1;
            }
        }
    }

    public static int indexOfSecondSpace(String name) {
        for(int i = 0; i < string.length() - 1; i++) {
            char nextNiceChar = charAt(i);
            if(nextNiceChar == )
        }

    }
}